version: "3.7"

secrets:
  DJANGO_SECRET_KEY:
    external: true
  MYSQL_PASSWORD:
      external: true
  MARIADB_PASSWORD:
    external: true
  MARIADB_ROOT_PASSWORD:
    external: true


services:
  nginx:
    image: nginx:1.19.5
    networks:
      - network
    volumes:
      - /home/django_course/nginx.conf:/etc/nginx/nginx.conf
      - static-volume:/data/static/
      - media-volume:/data/media/
    ports:
      - 80:80

  django_container_gunicorn:
    image: <본인이 만든 도커파일 이름:이미지번호>
    networks:
      - network
    volumes:
      - static-volume:/home/whobetter/staticfiles
      - media-volume:/home/whobetter/media
    secrets:
      - MYSQL_PASSWORD
      - DJANGO_SECRET_KEY

  mariadb:
    image: mariadb:10.5
    networks:
      - network
    volumes:
      - maria-database:/var/lib/mysql
    secrets:
      - MARIADB_PASSWORD
      - MARIADB_ROOT_PASSWORD


networks:
  network:

volumes:
  static-volume:
  media-volume:
  maria-database: