# Generated by Django 3.2.7 on 2022-03-01 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('promiseapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidate',
            name='slogan',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='depart',
            name='construction',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='depart',
            name='corona',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='depart',
            name='culture',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='depart',
            name='economy',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='depart',
            name='edu',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='depart',
            name='environ',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='depart',
            name='military',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='depart',
            name='politics',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='depart',
            name='realty',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='depart',
            name='science',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
