# Generated by Django 3.2.7 on 2022-03-01 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('promiseapp', '0002_auto_20220301_0825'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidate',
            name='image',
            field=models.ImageField(null=True, upload_to='promise/'),
        ),
    ]
